"""initial schema"""
from alembic import op
import sqlalchemy as sa
revision = "0001"; down_revision = None; branch_labels = None; depends_on = None
def upgrade():
    op.create_table("accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("email", sa.String(320), nullable=False), sa.Column("username", sa.String(320), nullable=False), sa.Column("password_encrypted", sa.Text(), nullable=False), sa.Column("imap_host", sa.String(255), nullable=False), sa.Column("imap_port", sa.Integer(), nullable=False), sa.Column("imap_ssl", sa.Boolean(), nullable=False), sa.Column("smtp_host", sa.String(255), nullable=False), sa.Column("smtp_port", sa.Integer(), nullable=False), sa.Column("smtp_ssl", sa.Boolean(), nullable=False), sa.Column("smtp_username", sa.String(320), nullable=False), sa.Column("smtp_password_encrypted", sa.Text(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("messages", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("account_id", sa.Integer(), sa.ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("folder", sa.String(255), nullable=False), sa.Column("uid", sa.BigInteger(), nullable=False), sa.Column("message_id", sa.String(998)), sa.Column("subject", sa.Text(), nullable=False), sa.Column("sender", sa.Text(), nullable=False), sa.Column("recipients", sa.Text(), nullable=False), sa.Column("cc", sa.Text(), nullable=False), sa.Column("bcc", sa.Text(), nullable=False), sa.Column("sent_at", sa.DateTime(timezone=True)), sa.Column("size", sa.BigInteger(), nullable=False), sa.Column("html_body", sa.Text(), nullable=False), sa.Column("text_body", sa.Text(), nullable=False), sa.Column("is_read", sa.Boolean(), nullable=False), sa.Column("is_important", sa.Boolean(), nullable=False), sa.UniqueConstraint("account_id", "folder", "uid"))
    op.create_index("ix_messages_account_id", "messages", ["account_id"]); op.create_index("ix_messages_folder", "messages", ["folder"]); op.create_index("ix_messages_sent_at", "messages", ["sent_at"]); op.create_index("ix_messages_is_read", "messages", ["is_read"])
    op.create_table("attachments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("message_id", sa.Integer(), sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=False), sa.Column("filename", sa.Text(), nullable=False), sa.Column("content_type", sa.String(255), nullable=False), sa.Column("size", sa.BigInteger(), nullable=False), sa.Column("content", sa.LargeBinary(), nullable=False)); op.create_index("ix_attachments_message_id", "attachments", ["message_id"])
    op.create_table("action_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("level", sa.String(20), nullable=False), sa.Column("action", sa.String(80), nullable=False), sa.Column("details", sa.Text(), nullable=False)); op.create_index("ix_action_logs_created_at", "action_logs", ["created_at"])
def downgrade(): op.drop_table("action_logs"); op.drop_table("attachments"); op.drop_table("messages"); op.drop_table("accounts")

